# Generated by Django 3.0.4 on 2021-01-27 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ticker_Minute_USD_JPY',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.DateTimeField(verbose_name='時間')),
                ('open', models.FloatField(verbose_name='始値')),
                ('close', models.FloatField(verbose_name='終値')),
                ('high', models.FloatField(verbose_name='最高値')),
                ('low', models.FloatField(verbose_name='最低値')),
                ('volume', models.IntegerField(verbose_name='ティック数')),
            ],
        ),
    ]
